[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3 --before usb-reset --after hard-reset"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=none",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
